//! chuk-train-agent — M0 join loop (spec §7).
//!
//! Runs identically on Colab, a Vast container, or any Linux box:
//!
//!     chuk-train-agent --url wss://train.example.com/ws/agent --token <JOIN_TOKEN>
//!
//! Dials OUT to the control plane, registers detected hardware, heartbeats,
//! executes assigned shell runs, streams stdout/stderr lines back, reconnects
//! with exponential backoff.
//!
//! M0 semantics (deliberate): one run in flight; logs are dropped while the
//! control plane is unreachable; if the session drops mid-run the child
//! process is killed — the control plane requeues the run anyway, so this
//! keeps both sides' view consistent until M1 adds buffering + resume.

mod hardware;
mod job;

use anyhow::{Context, Result};
use chuk_train_proto::{
    AgentToCp, CpToAgent, WorkerId, HEARTBEAT_INTERVAL, RECONNECT_BACKOFF_MAX,
    RECONNECT_BACKOFF_MIN,
};
use clap::Parser;
use futures_util::{SinkExt, StreamExt};
use tokio::sync::mpsc;
use tokio_tungstenite::connect_async;
use tokio_tungstenite::tungstenite::Message;
use tracing::{info, warn};

const LABEL_SEPARATOR: char = ',';

#[derive(Parser, Debug)]
#[command(name = "chuk-train-agent", about)]
struct Args {
    /// Control plane websocket URL, e.g. wss://train.example.com/ws/agent
    #[arg(long)]
    url: String,
    /// Join token (CHUK_TRAIN_JOIN_TOKEN on the control plane)
    #[arg(long)]
    token: String,
    /// Stable worker id; generated by the control plane if omitted
    #[arg(long)]
    worker_id: Option<String>,
    /// Comma-separated labels, e.g. colab,t4
    #[arg(long, default_value = "")]
    labels: String,
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let args = Args::parse();
    let labels: Vec<String> = args
        .labels
        .split(LABEL_SEPARATOR)
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .collect();

    let mut worker_id = args.worker_id.map(WorkerId::from);
    let mut backoff = RECONNECT_BACKOFF_MIN;
    loop {
        match session(&args.url, &args.token, worker_id.clone(), &labels).await {
            Ok(assigned_id) => {
                // Keep the id the control plane assigned so reconnects
                // present the same worker.
                worker_id = Some(assigned_id);
                backoff = RECONNECT_BACKOFF_MIN;
            }
            Err(error) => {
                warn!(%error, "session error");
            }
        }
        info!(delay_s = backoff.as_secs(), "reconnecting after backoff");
        tokio::time::sleep(backoff).await;
        backoff = (backoff * 2).min(RECONNECT_BACKOFF_MAX);
    }
}

/// One websocket session: register, then message loop until the socket dies.
/// Returns the worker id the control plane confirmed.
async fn session(
    url: &str,
    token: &str,
    worker_id: Option<WorkerId>,
    labels: &[String],
) -> Result<WorkerId> {
    let (socket, _response) = connect_async(url).await.context("connecting")?;
    let (mut sink, mut stream) = socket.split();

    let register = AgentToCp::Register {
        token: token.to_owned(),
        worker_id,
        labels: labels.to_vec(),
        hardware: hardware::detect().await,
    };
    sink.send(to_frame(&register)?)
        .await
        .context("sending register")?;

    let confirmed_id = match next_message(&mut stream).await {
        Some(CpToAgent::Registered { worker_id }) => worker_id,
        Some(CpToAgent::Rejected { reason }) => anyhow::bail!("registration rejected: {reason}"),
        other => anyhow::bail!("unexpected registration response: {other:?}"),
    };
    info!(worker = %confirmed_id, "registered");

    // Job tasks talk back through this channel; the select loop owns the sink.
    let (tx, mut outbound) = mpsc::unbounded_channel::<AgentToCp>();
    let mut heartbeat = tokio::time::interval(HEARTBEAT_INTERVAL);
    heartbeat.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
    // Current job slot; aborting the handle kills the child (kill_on_drop).
    let mut current: Option<job::RunningJob> = None;

    let session_result = loop {
        tokio::select! {
            _ = heartbeat.tick() => {
                if sink.send(to_frame(&AgentToCp::Heartbeat)?).await.is_err() {
                    break Ok(());
                }
            }
            msg = outbound.recv() => {
                let msg = msg.expect("tx lives in this scope");
                if sink.send(to_frame(&msg)?).await.is_err() {
                    break Ok(());
                }
            }
            inbound = next_message(&mut stream) => match inbound {
                Some(CpToAgent::Assign { job }) => {
                    if current.as_ref().is_some_and(|j| !j.is_finished()) {
                        // The control plane never double-assigns; if it does,
                        // refuse loudly rather than corrupt the slot.
                        warn!(run = %job.run_id, "assign received while busy; ignoring");
                        continue;
                    }
                    info!(run = %job.run_id, "assigned");
                    current = Some(job::spawn(job, tx.clone()));
                }
                Some(CpToAgent::Cancel { run_id }) => {
                    if let Some(job) = current.take() {
                        info!(run = %run_id, "cancelling");
                        job.abort();
                    }
                }
                Some(CpToAgent::Registered { .. }) | Some(CpToAgent::Rejected { .. }) => {
                    warn!("unexpected control message mid-session; ignoring");
                }
                None => break Ok(()),
            },
        }
    };

    // Session over: kill any in-flight job so our state matches the control
    // plane's (it requeues the run on disconnect).
    if let Some(job) = current.take() {
        if !job.is_finished() {
            warn!("session dropped mid-run; killing child (control plane requeues)");
        }
        job.abort();
    }
    session_result.map(|_| confirmed_id)
}

async fn next_message(
    stream: &mut (impl StreamExt<Item = tokio_tungstenite::tungstenite::Result<Message>> + Unpin),
) -> Option<CpToAgent> {
    while let Some(frame) = stream.next().await {
        match frame {
            Ok(Message::Text(text)) => match serde_json::from_str::<CpToAgent>(text.as_str()) {
                Ok(msg) => return Some(msg),
                Err(error) => warn!(%error, "unparseable control message; skipping"),
            },
            Ok(Message::Close(_)) | Err(_) => return None,
            Ok(_) => {}
        }
    }
    None
}

fn to_frame(msg: &AgentToCp) -> Result<Message> {
    Ok(Message::Text(serde_json::to_string(msg)?.into()))
}
